import numpy as np
a=np.zeros((2,4))
b=np.ones((2,2,3))
c=np.full((2,3,4), 10)
print(a)
print(b)
print(c)
#volver lista a un array
d=np.array([[1,2,3],[4,5,6]])
print(d)
print(np.linspace(0,9,num=10))
print(np.random.rand(2,3,4))
print(np.random.randn(2,4))
new=np.array([[1,2,3,4], [5,6,7,8]])
print(new[1,3])
print(new[:,2])
x=np.arange(28)
print(x)
x.shape=(7,4)
print(x)
print(x.ravel())#lo vuelve unidimensional
#FUNCIONES ESTADISTICAS EN NUMPY
array1=np.arange(1,20,2)
np.square(array1)
np.sqrt(array1)
print(array1)
print(array1.mean())
print(array1.sum())
print(dir(array1))